// flow-typed signature: d723c42a5b5e80de67a7dc916cb185cc
// flow-typed version: <<STUB>>/csv-parse_v^1.1.7/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv-parse/lib/index' {
  declare module.exports: any;
}

declare module 'csv-parse/lib/sync' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/callback' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/columns-discovery' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/comment' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/fs_read' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/objname' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/pipe' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/stream' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/sync' {
  declare module.exports: any;
}

declare module 'csv-parse/samples/tsv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv-parse/lib/index.js' {
  declare module.exports: $Exports<'csv-parse/lib/index'>;
}
declare module 'csv-parse/lib/sync.js' {
  declare module.exports: $Exports<'csv-parse/lib/sync'>;
}
declare module 'csv-parse/samples/callback.js' {
  declare module.exports: $Exports<'csv-parse/samples/callback'>;
}
declare module 'csv-parse/samples/columns-discovery.js' {
  declare module.exports: $Exports<'csv-parse/samples/columns-discovery'>;
}
declare module 'csv-parse/samples/comment.js' {
  declare module.exports: $Exports<'csv-parse/samples/comment'>;
}
declare module 'csv-parse/samples/fs_read.js' {
  declare module.exports: $Exports<'csv-parse/samples/fs_read'>;
}
declare module 'csv-parse/samples/objname.js' {
  declare module.exports: $Exports<'csv-parse/samples/objname'>;
}
declare module 'csv-parse/samples/pipe.js' {
  declare module.exports: $Exports<'csv-parse/samples/pipe'>;
}
declare module 'csv-parse/samples/stream.js' {
  declare module.exports: $Exports<'csv-parse/samples/stream'>;
}
declare module 'csv-parse/samples/sync.js' {
  declare module.exports: $Exports<'csv-parse/samples/sync'>;
}
declare module 'csv-parse/samples/tsv.js' {
  declare module.exports: $Exports<'csv-parse/samples/tsv'>;
}
