// flow-typed signature: 7e89d08085dd5174b4153205a2e1bc41
// flow-typed version: <<STUB>>/nopt_v^3.0.6/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nopt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nopt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nopt/bin/nopt' {
  declare module.exports: any;
}

declare module 'nopt/examples/my-program' {
  declare module.exports: any;
}

declare module 'nopt/lib/nopt' {
  declare module.exports: any;
}

declare module 'nopt/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nopt/bin/nopt.js' {
  declare module.exports: $Exports<'nopt/bin/nopt'>;
}
declare module 'nopt/examples/my-program.js' {
  declare module.exports: $Exports<'nopt/examples/my-program'>;
}
declare module 'nopt/lib/nopt.js' {
  declare module.exports: $Exports<'nopt/lib/nopt'>;
}
declare module 'nopt/test/basic.js' {
  declare module.exports: $Exports<'nopt/test/basic'>;
}
