// flow-typed signature: 9337082c62071efdaf542d304d4bf720
// flow-typed version: <<STUB>>/xml_v^1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'xml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xml/examples/examples' {
  declare module.exports: any;
}

declare module 'xml/examples/server' {
  declare module.exports: any;
}

declare module 'xml/lib/escapeForXML' {
  declare module.exports: any;
}

declare module 'xml/lib/xml' {
  declare module.exports: any;
}

declare module 'xml/test/xml.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xml/examples/examples.js' {
  declare module.exports: $Exports<'xml/examples/examples'>;
}
declare module 'xml/examples/server.js' {
  declare module.exports: $Exports<'xml/examples/server'>;
}
declare module 'xml/lib/escapeForXML.js' {
  declare module.exports: $Exports<'xml/lib/escapeForXML'>;
}
declare module 'xml/lib/xml.js' {
  declare module.exports: $Exports<'xml/lib/xml'>;
}
declare module 'xml/test/xml.test.js' {
  declare module.exports: $Exports<'xml/test/xml.test'>;
}
